[versions]
kotlin = "2.3.0"

[libraries]
typesafe-config = { module = "com.typesafe:config", version = "1.4.5" }

logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.27" }

kord-core = { module = "dev.kord:kord-core", version = "0.17.0" }

kord-emoji = { module = "dev.kord.x:emoji", version = "0.5.0"}

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }

kotlinx-serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version = "1.10.0" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
